// Curated emoji set for `:shortcode` autocomplete. `n` is the primary
// shortcode; `k` is extra search keywords (synonyms, related terms).

export interface EmojiEntry {
  c: string
  n: string
  k?: string[]
}

export const EMOJIS: EmojiEntry[] = [
  // Smileys & emotion
  { c: '😀', n: 'grinning', k: ['happy', 'smile'] },
  { c: '😃', n: 'smiley', k: ['happy', 'joy'] },
  { c: '😄', n: 'smile', k: ['happy', 'joy'] },
  { c: '😁', n: 'grin', k: ['happy'] },
  { c: '😆', n: 'laughing', k: ['lol', 'satisfied'] },
  { c: '😅', n: 'sweat_smile', k: ['relief'] },
  { c: '🤣', n: 'rofl', k: ['rolling', 'laughing'] },
  { c: '😂', n: 'joy', k: ['tears', 'laugh', 'cry'] },
  { c: '🙂', n: 'slight_smile', k: ['smile'] },
  { c: '🙃', n: 'upside_down', k: ['flipped'] },
  { c: '😉', n: 'wink' },
  { c: '😊', n: 'blush', k: ['smile'] },
  { c: '😇', n: 'innocent', k: ['halo', 'angel'] },
  { c: '🥰', n: 'smiling_face_with_hearts', k: ['love'] },
  { c: '😍', n: 'heart_eyes', k: ['love'] },
  { c: '🤩', n: 'star_struck', k: ['excited'] },
  { c: '😘', n: 'kissing_heart', k: ['kiss', 'love'] },
  { c: '😗', n: 'kissing' },
  { c: '😚', n: 'kissing_closed_eyes' },
  { c: '😙', n: 'kissing_smiling_eyes' },
  { c: '🥲', n: 'smiling_face_with_tear' },
  { c: '😋', n: 'yum', k: ['tasty', 'delicious'] },
  { c: '😛', n: 'stuck_out_tongue', k: ['tongue'] },
  { c: '😜', n: 'stuck_out_tongue_winking_eye' },
  { c: '🤪', n: 'zany_face', k: ['crazy'] },
  { c: '😝', n: 'stuck_out_tongue_closed_eyes' },
  { c: '🤑', n: 'money_mouth', k: ['rich'] },
  { c: '🤗', n: 'hugs', k: ['hug'] },
  { c: '🤭', n: 'hand_over_mouth', k: ['oops'] },
  { c: '🤫', n: 'shushing_face', k: ['quiet', 'shh'] },
  { c: '🤔', n: 'thinking', k: ['think', 'hmm'] },
  { c: '🤐', n: 'zipper_mouth', k: ['silence'] },
  { c: '🤨', n: 'raised_eyebrow', k: ['suspicious'] },
  { c: '😐', n: 'neutral_face' },
  { c: '😑', n: 'expressionless' },
  { c: '😶', n: 'no_mouth' },
  { c: '😏', n: 'smirk' },
  { c: '😒', n: 'unamused' },
  { c: '🙄', n: 'roll_eyes' },
  { c: '😬', n: 'grimacing' },
  { c: '🤥', n: 'lying_face', k: ['pinocchio'] },
  { c: '😌', n: 'relieved' },
  { c: '😔', n: 'pensive' },
  { c: '😪', n: 'sleepy' },
  { c: '🤤', n: 'drooling_face' },
  { c: '😴', n: 'sleeping', k: ['zzz'] },
  { c: '😷', n: 'mask', k: ['sick'] },
  { c: '🤒', n: 'thermometer_face', k: ['sick'] },
  { c: '🤕', n: 'bandage_face', k: ['hurt'] },
  { c: '🤢', n: 'nauseated_face' },
  { c: '🤮', n: 'vomiting_face' },
  { c: '🤧', n: 'sneezing_face' },
  { c: '🥵', n: 'hot_face' },
  { c: '🥶', n: 'cold_face' },
  { c: '🥴', n: 'woozy_face' },
  { c: '😵', n: 'dizzy_face' },
  { c: '🤯', n: 'exploding_head', k: ['mind', 'blown'] },
  { c: '🤠', n: 'cowboy' },
  { c: '🥳', n: 'partying_face', k: ['party'] },
  { c: '🥸', n: 'disguised_face' },
  { c: '😎', n: 'sunglasses', k: ['cool'] },
  { c: '🤓', n: 'nerd' },
  { c: '🧐', n: 'monocle' },
  { c: '😕', n: 'confused' },
  { c: '😟', n: 'worried' },
  { c: '🙁', n: 'slight_frown' },
  { c: '☹️', n: 'frowning' },
  { c: '😮', n: 'open_mouth' },
  { c: '😯', n: 'hushed' },
  { c: '😲', n: 'astonished' },
  { c: '😳', n: 'flushed' },
  { c: '🥺', n: 'pleading_face' },
  { c: '😦', n: 'frowning_open' },
  { c: '😧', n: 'anguished' },
  { c: '😨', n: 'fearful', k: ['scared'] },
  { c: '😰', n: 'cold_sweat' },
  { c: '😥', n: 'disappointed_relieved' },
  { c: '😢', n: 'cry' },
  { c: '😭', n: 'sob', k: ['cry'] },
  { c: '😱', n: 'scream' },
  { c: '😖', n: 'confounded' },
  { c: '😣', n: 'persevere' },
  { c: '😞', n: 'disappointed' },
  { c: '😓', n: 'sweat' },
  { c: '😩', n: 'weary' },
  { c: '😫', n: 'tired_face' },
  { c: '🥱', n: 'yawning_face' },
  { c: '😤', n: 'triumph' },
  { c: '😡', n: 'rage', k: ['angry'] },
  { c: '😠', n: 'angry', k: ['mad'] },
  { c: '🤬', n: 'cursing_face' },
  { c: '😈', n: 'smiling_imp' },
  { c: '👿', n: 'imp' },
  { c: '💀', n: 'skull' },
  { c: '☠️', n: 'skull_and_crossbones' },
  { c: '💩', n: 'poop', k: ['shit'] },
  { c: '🤡', n: 'clown' },
  { c: '👹', n: 'japanese_ogre' },
  { c: '👺', n: 'goblin' },
  { c: '👻', n: 'ghost' },
  { c: '👽', n: 'alien' },
  { c: '👾', n: 'space_invader' },
  { c: '🤖', n: 'robot' },
  { c: '😺', n: 'smiley_cat' },
  { c: '😸', n: 'smile_cat' },
  { c: '😹', n: 'joy_cat' },
  { c: '😻', n: 'heart_eyes_cat' },
  { c: '😼', n: 'smirk_cat' },
  { c: '😽', n: 'kissing_cat' },
  { c: '🙀', n: 'scream_cat' },
  { c: '😿', n: 'crying_cat' },
  { c: '😾', n: 'pouting_cat' },

  // Hearts & symbols
  { c: '❤️', n: 'heart', k: ['love'] },
  { c: '🧡', n: 'orange_heart' },
  { c: '💛', n: 'yellow_heart' },
  { c: '💚', n: 'green_heart' },
  { c: '💙', n: 'blue_heart' },
  { c: '💜', n: 'purple_heart' },
  { c: '🖤', n: 'black_heart' },
  { c: '🤍', n: 'white_heart' },
  { c: '🤎', n: 'brown_heart' },
  { c: '💔', n: 'broken_heart' },
  { c: '❣️', n: 'heart_exclamation' },
  { c: '💕', n: 'two_hearts' },
  { c: '💞', n: 'revolving_hearts' },
  { c: '💓', n: 'heartbeat' },
  { c: '💗', n: 'heartpulse' },
  { c: '💖', n: 'sparkling_heart' },
  { c: '💘', n: 'cupid' },
  { c: '💝', n: 'gift_heart' },
  { c: '💟', n: 'heart_decoration' },
  { c: '♥️', n: 'hearts' },
  { c: '💯', n: '100', k: ['hundred'] },
  { c: '💢', n: 'anger' },
  { c: '💥', n: 'boom', k: ['explosion'] },
  { c: '💫', n: 'dizzy' },
  { c: '💦', n: 'sweat_drops' },
  { c: '💨', n: 'dash' },
  { c: '🕳️', n: 'hole' },
  { c: '💬', n: 'speech_balloon' },
  { c: '🗨️', n: 'left_speech_bubble' },
  { c: '🗯️', n: 'anger_bubble' },
  { c: '💭', n: 'thought_balloon' },
  { c: '💤', n: 'zzz', k: ['sleep'] },

  // Hands & people
  { c: '👋', n: 'wave', k: ['hi', 'bye'] },
  { c: '🤚', n: 'raised_back_hand' },
  { c: '🖐️', n: 'raised_hand_with_fingers_splayed' },
  { c: '✋', n: 'hand', k: ['raised'] },
  { c: '🖖', n: 'vulcan_salute', k: ['spock'] },
  { c: '👌', n: 'ok_hand' },
  { c: '🤌', n: 'pinched_fingers' },
  { c: '🤏', n: 'pinching_hand' },
  { c: '✌️', n: 'peace', k: ['victory'] },
  { c: '🤞', n: 'crossed_fingers' },
  { c: '🤟', n: 'love_you_gesture' },
  { c: '🤘', n: 'metal', k: ['rock'] },
  { c: '🤙', n: 'call_me_hand' },
  { c: '👈', n: 'point_left' },
  { c: '👉', n: 'point_right' },
  { c: '👆', n: 'point_up_2' },
  { c: '🖕', n: 'middle_finger' },
  { c: '👇', n: 'point_down' },
  { c: '☝️', n: 'point_up' },
  { c: '👍', n: 'thumbsup', k: ['like', '+1'] },
  { c: '👎', n: 'thumbsdown', k: ['dislike', '-1'] },
  { c: '✊', n: 'fist', k: ['punch'] },
  { c: '👊', n: 'facepunch' },
  { c: '🤛', n: 'left_facing_fist' },
  { c: '🤜', n: 'right_facing_fist' },
  { c: '👏', n: 'clap' },
  { c: '🙌', n: 'raised_hands', k: ['praise'] },
  { c: '👐', n: 'open_hands' },
  { c: '🤲', n: 'palms_up_together' },
  { c: '🤝', n: 'handshake' },
  { c: '🙏', n: 'pray', k: ['please', 'thanks'] },
  { c: '💅', n: 'nail_care' },
  { c: '🤳', n: 'selfie' },
  { c: '💪', n: 'muscle', k: ['strong', 'flex'] },
  { c: '🦾', n: 'mechanical_arm' },
  { c: '🦿', n: 'mechanical_leg' },
  { c: '🦵', n: 'leg' },
  { c: '🦶', n: 'foot' },
  { c: '👂', n: 'ear' },
  { c: '🦻', n: 'ear_with_hearing_aid' },
  { c: '👃', n: 'nose' },
  { c: '🧠', n: 'brain' },
  { c: '🫀', n: 'anatomical_heart' },
  { c: '🫁', n: 'lungs' },
  { c: '🦷', n: 'tooth' },
  { c: '🦴', n: 'bone' },
  { c: '👀', n: 'eyes' },
  { c: '👁️', n: 'eye' },
  { c: '👅', n: 'tongue' },
  { c: '👄', n: 'lips' },
  { c: '👶', n: 'baby' },
  { c: '🧒', n: 'child' },
  { c: '👦', n: 'boy' },
  { c: '👧', n: 'girl' },
  { c: '🧑', n: 'person' },
  { c: '👱', n: 'blond_haired_person' },
  { c: '👨', n: 'man' },
  { c: '🧔', n: 'bearded_person' },
  { c: '👩', n: 'woman' },
  { c: '🧓', n: 'older_person' },
  { c: '👴', n: 'older_man' },
  { c: '👵', n: 'older_woman' },
  { c: '🙍', n: 'person_frowning' },
  { c: '🙎', n: 'person_pouting' },
  { c: '🙅', n: 'no_good' },
  { c: '🙆', n: 'ok_person' },
  { c: '💁', n: 'tipping_hand' },
  { c: '🙋', n: 'raising_hand' },
  { c: '🧏', n: 'deaf_person' },
  { c: '🙇', n: 'bow' },
  { c: '🤦', n: 'facepalm' },
  { c: '🤷', n: 'shrug' },

  // Roles & activities
  { c: '👮', n: 'police' },
  { c: '🕵️', n: 'detective' },
  { c: '💂', n: 'guard' },
  { c: '🥷', n: 'ninja' },
  { c: '👷', n: 'construction_worker' },
  { c: '🤴', n: 'prince' },
  { c: '👸', n: 'princess' },
  { c: '🧕', n: 'woman_with_headscarf' },
  { c: '🤵', n: 'person_in_tuxedo' },
  { c: '👰', n: 'bride' },
  { c: '🤰', n: 'pregnant_woman' },
  { c: '🤱', n: 'breast_feeding' },
  { c: '👼', n: 'angel' },
  { c: '🎅', n: 'santa' },
  { c: '🤶', n: 'mrs_claus' },
  { c: '🦸', n: 'superhero' },
  { c: '🦹', n: 'supervillain' },
  { c: '🧙', n: 'mage', k: ['wizard'] },
  { c: '🧚', n: 'fairy' },
  { c: '🧛', n: 'vampire' },
  { c: '🧜', n: 'merperson', k: ['mermaid'] },
  { c: '🧝', n: 'elf' },
  { c: '🧞', n: 'genie' },
  { c: '🧟', n: 'zombie' },

  // Nature & animals
  { c: '🐶', n: 'dog' },
  { c: '🐱', n: 'cat' },
  { c: '🐭', n: 'mouse' },
  { c: '🐹', n: 'hamster' },
  { c: '🐰', n: 'rabbit' },
  { c: '🦊', n: 'fox' },
  { c: '🐻', n: 'bear' },
  { c: '🐼', n: 'panda' },
  { c: '🐨', n: 'koala' },
  { c: '🐯', n: 'tiger' },
  { c: '🦁', n: 'lion' },
  { c: '🐮', n: 'cow' },
  { c: '🐷', n: 'pig' },
  { c: '🐽', n: 'pig_nose' },
  { c: '🐸', n: 'frog' },
  { c: '🐵', n: 'monkey_face' },
  { c: '🙈', n: 'see_no_evil' },
  { c: '🙉', n: 'hear_no_evil' },
  { c: '🙊', n: 'speak_no_evil' },
  { c: '🐒', n: 'monkey' },
  { c: '🐔', n: 'chicken' },
  { c: '🐧', n: 'penguin' },
  { c: '🐦', n: 'bird' },
  { c: '🐤', n: 'baby_chick' },
  { c: '🦆', n: 'duck' },
  { c: '🦅', n: 'eagle' },
  { c: '🦉', n: 'owl' },
  { c: '🦇', n: 'bat' },
  { c: '🐺', n: 'wolf' },
  { c: '🐗', n: 'boar' },
  { c: '🐴', n: 'horse' },
  { c: '🦄', n: 'unicorn' },
  { c: '🐝', n: 'bee' },
  { c: '🐛', n: 'bug', k: ['caterpillar'] },
  { c: '🦋', n: 'butterfly' },
  { c: '🐌', n: 'snail' },
  { c: '🐞', n: 'ladybug' },
  { c: '🐜', n: 'ant' },
  { c: '🦗', n: 'cricket' },
  { c: '🕷️', n: 'spider' },
  { c: '🕸️', n: 'spider_web' },
  { c: '🦂', n: 'scorpion' },
  { c: '🐢', n: 'turtle' },
  { c: '🐍', n: 'snake' },
  { c: '🦎', n: 'lizard' },
  { c: '🦖', n: 't_rex' },
  { c: '🦕', n: 'sauropod' },
  { c: '🐙', n: 'octopus' },
  { c: '🦑', n: 'squid' },
  { c: '🦐', n: 'shrimp' },
  { c: '🦀', n: 'crab' },
  { c: '🐡', n: 'blowfish' },
  { c: '🐠', n: 'tropical_fish' },
  { c: '🐟', n: 'fish' },
  { c: '🐬', n: 'dolphin' },
  { c: '🐳', n: 'whale' },
  { c: '🐋', n: 'whale2' },
  { c: '🦈', n: 'shark' },
  { c: '🐊', n: 'crocodile' },
  { c: '🐅', n: 'tiger2' },
  { c: '🐆', n: 'leopard' },
  { c: '🦓', n: 'zebra' },
  { c: '🦍', n: 'gorilla' },
  { c: '🦧', n: 'orangutan' },
  { c: '🐘', n: 'elephant' },
  { c: '🦏', n: 'rhino' },
  { c: '🦛', n: 'hippopotamus' },
  { c: '🐪', n: 'camel' },
  { c: '🦒', n: 'giraffe' },
  { c: '🦘', n: 'kangaroo' },
  { c: '🐃', n: 'water_buffalo' },
  { c: '🐂', n: 'ox' },
  { c: '🐄', n: 'cow2' },
  { c: '🐎', n: 'racehorse' },
  { c: '🐖', n: 'pig2' },
  { c: '🐏', n: 'ram' },
  { c: '🐑', n: 'sheep' },
  { c: '🐐', n: 'goat' },
  { c: '🦌', n: 'deer' },
  { c: '🐕', n: 'dog2' },
  { c: '🦮', n: 'guide_dog' },
  { c: '🐩', n: 'poodle' },
  { c: '🐈', n: 'cat2' },
  { c: '🦃', n: 'turkey' },
  { c: '🦚', n: 'peacock' },
  { c: '🦜', n: 'parrot' },
  { c: '🦢', n: 'swan' },
  { c: '🦩', n: 'flamingo' },
  { c: '🕊️', n: 'dove' },
  { c: '🐇', n: 'rabbit2' },
  { c: '🦝', n: 'raccoon' },
  { c: '🦨', n: 'skunk' },
  { c: '🦡', n: 'badger' },
  { c: '🦦', n: 'otter' },
  { c: '🦥', n: 'sloth' },
  { c: '🐁', n: 'mouse2' },
  { c: '🐀', n: 'rat' },
  { c: '🐿️', n: 'chipmunk' },
  { c: '🦔', n: 'hedgehog' },

  // Plants & nature
  { c: '🌵', n: 'cactus' },
  { c: '🎄', n: 'christmas_tree' },
  { c: '🌲', n: 'evergreen_tree' },
  { c: '🌳', n: 'deciduous_tree' },
  { c: '🌴', n: 'palm_tree' },
  { c: '🌱', n: 'seedling' },
  { c: '🌿', n: 'herb' },
  { c: '☘️', n: 'shamrock' },
  { c: '🍀', n: 'four_leaf_clover' },
  { c: '🎍', n: 'bamboo' },
  { c: '🎋', n: 'tanabata_tree' },
  { c: '🍃', n: 'leaves' },
  { c: '🍂', n: 'fallen_leaf' },
  { c: '🍁', n: 'maple_leaf' },
  { c: '🍄', n: 'mushroom' },
  { c: '🌾', n: 'rice' },
  { c: '💐', n: 'bouquet' },
  { c: '🌷', n: 'tulip' },
  { c: '🌹', n: 'rose' },
  { c: '🥀', n: 'wilted_flower' },
  { c: '🌺', n: 'hibiscus' },
  { c: '🌸', n: 'cherry_blossom' },
  { c: '🌼', n: 'blossom' },
  { c: '🌻', n: 'sunflower' },
  { c: '🌞', n: 'sun_with_face' },
  { c: '🌝', n: 'full_moon_face' },
  { c: '🌛', n: 'first_quarter_moon_face' },
  { c: '🌜', n: 'last_quarter_moon_face' },
  { c: '🌚', n: 'new_moon_face' },
  { c: '🌕', n: 'full_moon' },
  { c: '🌖', n: 'waning_gibbous_moon' },
  { c: '🌗', n: 'last_quarter_moon' },
  { c: '🌘', n: 'waning_crescent_moon' },
  { c: '🌑', n: 'new_moon' },
  { c: '🌒', n: 'waxing_crescent_moon' },
  { c: '🌓', n: 'first_quarter_moon' },
  { c: '🌔', n: 'waxing_gibbous_moon' },
  { c: '🌙', n: 'crescent_moon' },
  { c: '🌎', n: 'earth_americas' },
  { c: '🌍', n: 'earth_africa' },
  { c: '🌏', n: 'earth_asia' },
  { c: '🪐', n: 'ringed_planet' },
  { c: '💫', n: 'dizzy_symbol', k: ['star'] },
  { c: '⭐', n: 'star' },
  { c: '🌟', n: 'star2', k: ['glowing'] },
  { c: '✨', n: 'sparkles' },
  { c: '⚡', n: 'zap', k: ['lightning'] },
  { c: '☄️', n: 'comet' },
  { c: '💥', n: 'collision' },
  { c: '🔥', n: 'fire' },
  { c: '🌪️', n: 'tornado' },
  { c: '🌈', n: 'rainbow' },
  { c: '☀️', n: 'sunny' },
  { c: '🌤️', n: 'partly_sunny' },
  { c: '⛅', n: 'partly_sunny_cloud' },
  { c: '🌥️', n: 'cloud_with_sun' },
  { c: '☁️', n: 'cloud' },
  { c: '🌦️', n: 'cloud_with_rain' },
  { c: '🌧️', n: 'cloud_rain' },
  { c: '⛈️', n: 'cloud_lightning_rain' },
  { c: '🌩️', n: 'cloud_lightning' },
  { c: '🌨️', n: 'cloud_snow' },
  { c: '❄️', n: 'snowflake' },
  { c: '☃️', n: 'snowman_with_snow' },
  { c: '⛄', n: 'snowman' },
  { c: '🌬️', n: 'wind_face' },
  { c: '💧', n: 'droplet' },
  { c: '💦', n: 'sweat' },
  { c: '🌊', n: 'ocean' },

  // Food & drink
  { c: '🍎', n: 'apple' },
  { c: '🍏', n: 'green_apple' },
  { c: '🍐', n: 'pear' },
  { c: '🍊', n: 'orange' },
  { c: '🍋', n: 'lemon' },
  { c: '🍌', n: 'banana' },
  { c: '🍉', n: 'watermelon' },
  { c: '🍇', n: 'grapes' },
  { c: '🍓', n: 'strawberry' },
  { c: '🫐', n: 'blueberries' },
  { c: '🍈', n: 'melon' },
  { c: '🍒', n: 'cherries' },
  { c: '🍑', n: 'peach' },
  { c: '🥭', n: 'mango' },
  { c: '🍍', n: 'pineapple' },
  { c: '🥥', n: 'coconut' },
  { c: '🥝', n: 'kiwi' },
  { c: '🍅', n: 'tomato' },
  { c: '🍆', n: 'eggplant' },
  { c: '🥑', n: 'avocado' },
  { c: '🥦', n: 'broccoli' },
  { c: '🥬', n: 'leafy_green' },
  { c: '🥒', n: 'cucumber' },
  { c: '🌶️', n: 'hot_pepper' },
  { c: '🫑', n: 'bell_pepper' },
  { c: '🌽', n: 'corn' },
  { c: '🥕', n: 'carrot' },
  { c: '🧄', n: 'garlic' },
  { c: '🧅', n: 'onion' },
  { c: '🥔', n: 'potato' },
  { c: '🍠', n: 'sweet_potato' },
  { c: '🥐', n: 'croissant' },
  { c: '🥯', n: 'bagel' },
  { c: '🍞', n: 'bread' },
  { c: '🥖', n: 'baguette' },
  { c: '🫓', n: 'flatbread' },
  { c: '🧀', n: 'cheese' },
  { c: '🥚', n: 'egg' },
  { c: '🍳', n: 'fried_egg' },
  { c: '🧈', n: 'butter' },
  { c: '🥞', n: 'pancakes' },
  { c: '🧇', n: 'waffle' },
  { c: '🥓', n: 'bacon' },
  { c: '🥩', n: 'cut_of_meat' },
  { c: '🍗', n: 'poultry_leg' },
  { c: '🍖', n: 'meat_on_bone' },
  { c: '🌭', n: 'hotdog' },
  { c: '🍔', n: 'hamburger' },
  { c: '🍟', n: 'fries' },
  { c: '🍕', n: 'pizza' },
  { c: '🥪', n: 'sandwich' },
  { c: '🥙', n: 'stuffed_flatbread' },
  { c: '🧆', n: 'falafel' },
  { c: '🌮', n: 'taco' },
  { c: '🌯', n: 'burrito' },
  { c: '🫔', n: 'tamale' },
  { c: '🥗', n: 'green_salad' },
  { c: '🥘', n: 'shallow_pan_of_food' },
  { c: '🫕', n: 'fondue' },
  { c: '🥫', n: 'canned_food' },
  { c: '🍝', n: 'spaghetti' },
  { c: '🍜', n: 'ramen' },
  { c: '🍲', n: 'stew' },
  { c: '🍛', n: 'curry' },
  { c: '🍣', n: 'sushi' },
  { c: '🍱', n: 'bento' },
  { c: '🥟', n: 'dumpling' },
  { c: '🦪', n: 'oyster' },
  { c: '🍤', n: 'fried_shrimp' },
  { c: '🍙', n: 'rice_ball' },
  { c: '🍚', n: 'rice' },
  { c: '🍘', n: 'rice_cracker' },
  { c: '🍥', n: 'fish_cake' },
  { c: '🥠', n: 'fortune_cookie' },
  { c: '🥮', n: 'moon_cake' },
  { c: '🍢', n: 'oden' },
  { c: '🍡', n: 'dango' },
  { c: '🍧', n: 'shaved_ice' },
  { c: '🍨', n: 'ice_cream' },
  { c: '🍦', n: 'icecream' },
  { c: '🥧', n: 'pie' },
  { c: '🧁', n: 'cupcake' },
  { c: '🍰', n: 'cake' },
  { c: '🎂', n: 'birthday' },
  { c: '🍮', n: 'custard' },
  { c: '🍭', n: 'lollipop' },
  { c: '🍬', n: 'candy' },
  { c: '🍫', n: 'chocolate_bar' },
  { c: '🍿', n: 'popcorn' },
  { c: '🍩', n: 'doughnut' },
  { c: '🍪', n: 'cookie' },
  { c: '🌰', n: 'chestnut' },
  { c: '🥜', n: 'peanuts' },
  { c: '🍯', n: 'honey_pot' },
  { c: '🥛', n: 'milk_glass' },
  { c: '🍼', n: 'baby_bottle' },
  { c: '☕', n: 'coffee' },
  { c: '🫖', n: 'teapot' },
  { c: '🍵', n: 'tea' },
  { c: '🧃', n: 'beverage_box' },
  { c: '🥤', n: 'cup_with_straw' },
  { c: '🧋', n: 'bubble_tea' },
  { c: '🍶', n: 'sake' },
  { c: '🍺', n: 'beer' },
  { c: '🍻', n: 'beers' },
  { c: '🥂', n: 'champagne_glass' },
  { c: '🍷', n: 'wine_glass' },
  { c: '🥃', n: 'tumbler_glass' },
  { c: '🍸', n: 'cocktail' },
  { c: '🍹', n: 'tropical_drink' },
  { c: '🍾', n: 'champagne' },
  { c: '🧊', n: 'ice_cube' },
  { c: '🥄', n: 'spoon' },
  { c: '🍴', n: 'fork_and_knife' },
  { c: '🍽️', n: 'plate_with_cutlery' },
  { c: '🥣', n: 'bowl_with_spoon' },
  { c: '🥡', n: 'takeout_box' },
  { c: '🥢', n: 'chopsticks' },
  { c: '🧂', n: 'salt' },

  // Travel & places
  { c: '🚗', n: 'car' },
  { c: '🚕', n: 'taxi' },
  { c: '🚙', n: 'suv' },
  { c: '🚌', n: 'bus' },
  { c: '🚎', n: 'trolleybus' },
  { c: '🏎️', n: 'racing_car' },
  { c: '🚓', n: 'police_car' },
  { c: '🚑', n: 'ambulance' },
  { c: '🚒', n: 'fire_engine' },
  { c: '🚐', n: 'minibus' },
  { c: '🚚', n: 'truck' },
  { c: '🚛', n: 'articulated_lorry' },
  { c: '🚜', n: 'tractor' },
  { c: '🛵', n: 'scooter' },
  { c: '🏍️', n: 'motorcycle' },
  { c: '🛺', n: 'auto_rickshaw' },
  { c: '🚲', n: 'bike' },
  { c: '🛴', n: 'kick_scooter' },
  { c: '🛹', n: 'skateboard' },
  { c: '🛼', n: 'roller_skate' },
  { c: '🚏', n: 'busstop' },
  { c: '🛣️', n: 'motorway' },
  { c: '🛤️', n: 'railway_track' },
  { c: '🛢️', n: 'oil_drum' },
  { c: '⛽', n: 'fuelpump' },
  { c: '🚨', n: 'rotating_light' },
  { c: '🚥', n: 'traffic_light' },
  { c: '🚦', n: 'vertical_traffic_light' },
  { c: '🛑', n: 'stop_sign' },
  { c: '🚧', n: 'construction' },
  { c: '⚓', n: 'anchor' },
  { c: '⛵', n: 'boat' },
  { c: '🛶', n: 'canoe' },
  { c: '🚤', n: 'speedboat' },
  { c: '🛳️', n: 'passenger_ship' },
  { c: '⛴️', n: 'ferry' },
  { c: '🛥️', n: 'motor_boat' },
  { c: '🚢', n: 'ship' },
  { c: '✈️', n: 'airplane' },
  { c: '🛩️', n: 'small_airplane' },
  { c: '🛫', n: 'airplane_departure' },
  { c: '🛬', n: 'airplane_arriving' },
  { c: '🪂', n: 'parachute' },
  { c: '💺', n: 'seat' },
  { c: '🚁', n: 'helicopter' },
  { c: '🚟', n: 'suspension_railway' },
  { c: '🚠', n: 'mountain_cableway' },
  { c: '🚡', n: 'aerial_tramway' },
  { c: '🛰️', n: 'satellite' },
  { c: '🚀', n: 'rocket' },
  { c: '🛸', n: 'flying_saucer' },

  // Activities & sports
  { c: '⚽', n: 'soccer' },
  { c: '🏀', n: 'basketball' },
  { c: '🏈', n: 'football' },
  { c: '⚾', n: 'baseball' },
  { c: '🥎', n: 'softball' },
  { c: '🎾', n: 'tennis' },
  { c: '🏐', n: 'volleyball' },
  { c: '🏉', n: 'rugby_football' },
  { c: '🥏', n: 'flying_disc' },
  { c: '🎱', n: '8ball' },
  { c: '🪀', n: 'yo_yo' },
  { c: '🏓', n: 'ping_pong' },
  { c: '🏸', n: 'badminton' },
  { c: '🏒', n: 'hockey' },
  { c: '🏑', n: 'field_hockey' },
  { c: '🥍', n: 'lacrosse' },
  { c: '🏏', n: 'cricket_game' },
  { c: '🥅', n: 'goal' },
  { c: '⛳', n: 'golf' },
  { c: '🪁', n: 'kite' },
  { c: '🏹', n: 'bow_and_arrow' },
  { c: '🎣', n: 'fishing_pole_and_fish' },
  { c: '🤿', n: 'diving_mask' },
  { c: '🥊', n: 'boxing_glove' },
  { c: '🥋', n: 'martial_arts_uniform' },
  { c: '🎽', n: 'running_shirt_with_sash' },
  { c: '🛹', n: 'skateboard2' },
  { c: '🛷', n: 'sled' },
  { c: '⛸️', n: 'ice_skate' },
  { c: '🥌', n: 'curling_stone' },
  { c: '🎿', n: 'ski' },
  { c: '⛷️', n: 'skier' },
  { c: '🏂', n: 'snowboarder' },
  { c: '🪂', n: 'parachute2' },
  { c: '🏋️', n: 'weight_lifter' },
  { c: '🤸', n: 'cartwheeling' },
  { c: '🤼', n: 'wrestling' },
  { c: '🤽', n: 'water_polo' },
  { c: '🤾', n: 'handball' },
  { c: '🏌️', n: 'golfer' },
  { c: '🏇', n: 'horse_racing' },
  { c: '🧘', n: 'person_in_lotus_position' },
  { c: '🏄', n: 'surfer' },
  { c: '🏊', n: 'swimmer' },
  { c: '🚣', n: 'rowboat' },
  { c: '🧗', n: 'climbing' },
  { c: '🚵', n: 'mountain_bicyclist' },
  { c: '🚴', n: 'bicyclist' },
  { c: '🏆', n: 'trophy' },
  { c: '🥇', n: '1st_place_medal' },
  { c: '🥈', n: '2nd_place_medal' },
  { c: '🥉', n: '3rd_place_medal' },
  { c: '🏅', n: 'sports_medal' },
  { c: '🎖️', n: 'military_medal' },
  { c: '🏵️', n: 'rosette' },
  { c: '🎗️', n: 'reminder_ribbon' },

  // Objects
  { c: '🎫', n: 'ticket' },
  { c: '🎟️', n: 'admission_tickets' },
  { c: '🎪', n: 'circus_tent' },
  { c: '🤹', n: 'juggling' },
  { c: '🎭', n: 'performing_arts' },
  { c: '🎨', n: 'art' },
  { c: '🎬', n: 'clapper' },
  { c: '🎤', n: 'microphone' },
  { c: '🎧', n: 'headphones' },
  { c: '🎼', n: 'musical_score' },
  { c: '🎵', n: 'musical_note' },
  { c: '🎶', n: 'notes' },
  { c: '🎹', n: 'musical_keyboard' },
  { c: '🥁', n: 'drum' },
  { c: '🎷', n: 'saxophone' },
  { c: '🎺', n: 'trumpet' },
  { c: '🎸', n: 'guitar' },
  { c: '🪕', n: 'banjo' },
  { c: '🎻', n: 'violin' },
  { c: '🎲', n: 'game_die' },
  { c: '♟️', n: 'chess_pawn' },
  { c: '🎯', n: 'dart' },
  { c: '🎳', n: 'bowling' },
  { c: '🎮', n: 'video_game' },
  { c: '🎰', n: 'slot_machine' },
  { c: '🧩', n: 'jigsaw' },
  { c: '📱', n: 'iphone' },
  { c: '📲', n: 'calling' },
  { c: '💻', n: 'computer' },
  { c: '⌨️', n: 'keyboard' },
  { c: '🖥️', n: 'desktop_computer' },
  { c: '🖨️', n: 'printer' },
  { c: '🖱️', n: 'computer_mouse' },
  { c: '🖲️', n: 'trackball' },
  { c: '🕹️', n: 'joystick' },
  { c: '🗜️', n: 'clamp' },
  { c: '💽', n: 'minidisc' },
  { c: '💾', n: 'floppy_disk' },
  { c: '💿', n: 'cd' },
  { c: '📀', n: 'dvd' },
  { c: '📼', n: 'vhs' },
  { c: '📷', n: 'camera' },
  { c: '📸', n: 'camera_flash' },
  { c: '📹', n: 'video_camera' },
  { c: '🎥', n: 'movie_camera' },
  { c: '📽️', n: 'film_projector' },
  { c: '🎞️', n: 'film_strip' },
  { c: '📞', n: 'telephone_receiver' },
  { c: '☎️', n: 'phone' },
  { c: '📟', n: 'pager' },
  { c: '📠', n: 'fax' },
  { c: '📺', n: 'tv' },
  { c: '📻', n: 'radio' },
  { c: '🎙️', n: 'studio_microphone' },
  { c: '🎚️', n: 'level_slider' },
  { c: '🎛️', n: 'control_knobs' },
  { c: '🧭', n: 'compass' },
  { c: '⏱️', n: 'stopwatch' },
  { c: '⏲️', n: 'timer_clock' },
  { c: '⏰', n: 'alarm_clock' },
  { c: '🕰️', n: 'mantelpiece_clock' },
  { c: '⌛', n: 'hourglass' },
  { c: '⏳', n: 'hourglass_flowing_sand' },
  { c: '📡', n: 'satellite_antenna' },
  { c: '🔋', n: 'battery' },
  { c: '🔌', n: 'electric_plug' },
  { c: '💡', n: 'bulb', k: ['idea'] },
  { c: '🔦', n: 'flashlight' },
  { c: '🕯️', n: 'candle' },
  { c: '🪔', n: 'diya_lamp' },
  { c: '🧯', n: 'fire_extinguisher' },
  { c: '🛢️', n: 'oil_drum2' },
  { c: '💸', n: 'money_with_wings' },
  { c: '💵', n: 'dollar' },
  { c: '💴', n: 'yen' },
  { c: '💶', n: 'euro' },
  { c: '💷', n: 'pound' },
  { c: '💰', n: 'moneybag' },
  { c: '💳', n: 'credit_card' },
  { c: '💎', n: 'gem' },
  { c: '⚖️', n: 'balance_scale' },
  { c: '🧰', n: 'toolbox' },
  { c: '🔧', n: 'wrench' },
  { c: '🔨', n: 'hammer' },
  { c: '⚒️', n: 'hammer_and_pick' },
  { c: '🛠️', n: 'hammer_and_wrench' },
  { c: '⛏️', n: 'pick' },
  { c: '🔩', n: 'nut_and_bolt' },
  { c: '⚙️', n: 'gear' },
  { c: '🧱', n: 'bricks' },
  { c: '⛓️', n: 'chains' },
  { c: '🧲', n: 'magnet' },
  { c: '🔫', n: 'gun' },
  { c: '💣', n: 'bomb' },
  { c: '🧨', n: 'firecracker' },
  { c: '🪓', n: 'axe' },
  { c: '🔪', n: 'knife' },
  { c: '🗡️', n: 'dagger' },
  { c: '⚔️', n: 'crossed_swords' },
  { c: '🛡️', n: 'shield' },
  { c: '🚬', n: 'smoking' },
  { c: '⚰️', n: 'coffin' },
  { c: '⚱️', n: 'urn' },
  { c: '🏺', n: 'amphora' },
  { c: '🔮', n: 'crystal_ball' },
  { c: '📿', n: 'prayer_beads' },
  { c: '🧿', n: 'nazar_amulet' },
  { c: '💈', n: 'barber' },
  { c: '⚗️', n: 'alembic' },
  { c: '🔭', n: 'telescope' },
  { c: '🔬', n: 'microscope' },
  { c: '🕳️', n: 'hole2' },
  { c: '🩹', n: 'adhesive_bandage' },
  { c: '🩺', n: 'stethoscope' },
  { c: '💊', n: 'pill' },
  { c: '💉', n: 'syringe' },
  { c: '🧬', n: 'dna' },
  { c: '🦠', n: 'microbe' },
  { c: '🧫', n: 'petri_dish' },
  { c: '🧪', n: 'test_tube' },
  { c: '🌡️', n: 'thermometer' },
  { c: '🧹', n: 'broom' },
  { c: '🧺', n: 'basket' },
  { c: '🧻', n: 'toilet_paper' },
  { c: '🚽', n: 'toilet' },
  { c: '🚰', n: 'potable_water' },
  { c: '🚿', n: 'shower' },
  { c: '🛁', n: 'bathtub' },
  { c: '🛀', n: 'bath' },
  { c: '🧼', n: 'soap' },
  { c: '🪒', n: 'razor' },
  { c: '🧽', n: 'sponge' },
  { c: '🧴', n: 'lotion_bottle' },
  { c: '🛎️', n: 'bellhop_bell' },
  { c: '🔑', n: 'key' },
  { c: '🗝️', n: 'old_key' },
  { c: '🚪', n: 'door' },
  { c: '🪑', n: 'chair' },
  { c: '🛋️', n: 'couch_and_lamp' },
  { c: '🛏️', n: 'bed' },
  { c: '🛌', n: 'sleeping_bed' },
  { c: '🧸', n: 'teddy_bear' },
  { c: '🖼️', n: 'frame_with_picture' },
  { c: '🛍️', n: 'shopping_bags' },
  { c: '🛒', n: 'shopping_cart' },
  { c: '🎁', n: 'gift' },
  { c: '🎈', n: 'balloon' },
  { c: '🎏', n: 'flags' },
  { c: '🎀', n: 'ribbon' },
  { c: '🎊', n: 'confetti_ball' },
  { c: '🎉', n: 'tada', k: ['party', 'celebrate'] },
  { c: '🎎', n: 'dolls' },
  { c: '🏮', n: 'izakaya_lantern' },
  { c: '🎐', n: 'wind_chime' },
  { c: '🧧', n: 'red_envelope' },
  { c: '✉️', n: 'envelope' },
  { c: '📩', n: 'envelope_with_arrow' },
  { c: '📨', n: 'incoming_envelope' },
  { c: '📧', n: 'email' },
  { c: '💌', n: 'love_letter' },
  { c: '📥', n: 'inbox_tray' },
  { c: '📤', n: 'outbox_tray' },
  { c: '📦', n: 'package' },
  { c: '🏷️', n: 'label' },
  { c: '📪', n: 'mailbox_closed' },
  { c: '📫', n: 'mailbox' },
  { c: '📬', n: 'mailbox_with_mail' },
  { c: '📭', n: 'mailbox_with_no_mail' },
  { c: '📮', n: 'postbox' },
  { c: '📯', n: 'postal_horn' },
  { c: '📜', n: 'scroll' },
  { c: '📃', n: 'page_with_curl' },
  { c: '📄', n: 'page_facing_up' },
  { c: '📑', n: 'bookmark_tabs' },
  { c: '🧾', n: 'receipt' },
  { c: '📊', n: 'bar_chart' },
  { c: '📈', n: 'chart_increasing' },
  { c: '📉', n: 'chart_decreasing' },
  { c: '🗒️', n: 'spiral_notepad' },
  { c: '🗓️', n: 'spiral_calendar' },
  { c: '📆', n: 'calendar' },
  { c: '📅', n: 'date' },
  { c: '🗑️', n: 'wastebasket' },
  { c: '📇', n: 'card_index' },
  { c: '🗃️', n: 'card_file_box' },
  { c: '🗳️', n: 'ballot_box' },
  { c: '🗄️', n: 'file_cabinet' },
  { c: '📋', n: 'clipboard' },
  { c: '📁', n: 'file_folder' },
  { c: '📂', n: 'open_file_folder' },
  { c: '🗂️', n: 'card_index_dividers' },
  { c: '🗞️', n: 'rolled_up_newspaper' },
  { c: '📰', n: 'newspaper' },
  { c: '📓', n: 'notebook' },
  { c: '📔', n: 'notebook_with_decorative_cover' },
  { c: '📒', n: 'ledger' },
  { c: '📕', n: 'closed_book' },
  { c: '📗', n: 'green_book' },
  { c: '📘', n: 'blue_book' },
  { c: '📙', n: 'orange_book' },
  { c: '📚', n: 'books' },
  { c: '📖', n: 'book' },
  { c: '🔖', n: 'bookmark' },
  { c: '🧷', n: 'safety_pin' },
  { c: '🔗', n: 'link' },
  { c: '📎', n: 'paperclip' },
  { c: '🖇️', n: 'paperclips' },
  { c: '📐', n: 'triangular_ruler' },
  { c: '📏', n: 'straight_ruler' },
  { c: '🧮', n: 'abacus' },
  { c: '📌', n: 'pushpin' },
  { c: '📍', n: 'round_pushpin' },
  { c: '✂️', n: 'scissors' },
  { c: '🖊️', n: 'pen' },
  { c: '🖋️', n: 'fountain_pen' },
  { c: '✒️', n: 'black_nib' },
  { c: '🖌️', n: 'paintbrush' },
  { c: '🖍️', n: 'crayon' },
  { c: '📝', n: 'memo', k: ['pencil'] },
  { c: '✏️', n: 'pencil' },
  { c: '🔍', n: 'mag', k: ['search'] },
  { c: '🔎', n: 'mag_right' },
  { c: '🔏', n: 'lock_with_ink_pen' },
  { c: '🔐', n: 'closed_lock_with_key' },
  { c: '🔒', n: 'lock' },
  { c: '🔓', n: 'unlock' },

  // Symbols
  { c: '✅', n: 'check' },
  { c: '❌', n: 'x', k: ['cross', 'no'] },
  { c: '❎', n: 'negative_squared_cross_mark' },
  { c: '✔️', n: 'heavy_check_mark' },
  { c: '☑️', n: 'ballot_box_with_check' },
  { c: '❓', n: 'question' },
  { c: '❔', n: 'grey_question' },
  { c: '❕', n: 'grey_exclamation' },
  { c: '❗', n: 'exclamation' },
  { c: '‼️', n: 'bangbang' },
  { c: '⁉️', n: 'interrobang' },
  { c: '⚠️', n: 'warning' },
  { c: '🚫', n: 'no_entry_sign' },
  { c: '🚷', n: 'no_pedestrians' },
  { c: '🚯', n: 'do_not_litter' },
  { c: '🚳', n: 'no_bicycles' },
  { c: '🚱', n: 'non_potable_water' },
  { c: '🔞', n: 'underage' },
  { c: '📵', n: 'no_mobile_phones' },
  { c: '🚭', n: 'no_smoking' },
  { c: '❇️', n: 'sparkle' },
  { c: '💠', n: 'diamond_shape_with_a_dot_inside' },
  { c: '🔶', n: 'large_orange_diamond' },
  { c: '🔷', n: 'large_blue_diamond' },
  { c: '🔸', n: 'small_orange_diamond' },
  { c: '🔹', n: 'small_blue_diamond' },
  { c: '🔺', n: 'small_red_triangle' },
  { c: '🔻', n: 'small_red_triangle_down' },
  { c: '🔼', n: 'arrow_up_small' },
  { c: '🔽', n: 'arrow_down_small' },
  { c: '⬆️', n: 'arrow_up' },
  { c: '⬇️', n: 'arrow_down' },
  { c: '⬅️', n: 'arrow_left' },
  { c: '➡️', n: 'arrow_right' },
  { c: '↗️', n: 'arrow_upper_right' },
  { c: '↘️', n: 'arrow_lower_right' },
  { c: '↙️', n: 'arrow_lower_left' },
  { c: '↖️', n: 'arrow_upper_left' },
  { c: '↕️', n: 'arrow_up_down' },
  { c: '↔️', n: 'left_right_arrow' },
  { c: '↩️', n: 'leftwards_arrow_with_hook' },
  { c: '↪️', n: 'arrow_right_hook' },
  { c: '🔃', n: 'arrows_clockwise' },
  { c: '🔄', n: 'arrows_counterclockwise' },
  { c: '🔁', n: 'repeat' },
  { c: '🔂', n: 'repeat_one' },
  { c: '🔀', n: 'shuffle' },
  { c: '▶️', n: 'arrow_forward' },
  { c: '⏸️', n: 'pause_button' },
  { c: '⏯️', n: 'play_or_pause_button' },
  { c: '⏹️', n: 'stop_button' },
  { c: '⏺️', n: 'record_button' },
  { c: '⏭️', n: 'next_track_button' },
  { c: '⏮️', n: 'previous_track_button' },
  { c: '⏩', n: 'fast_forward' },
  { c: '⏪', n: 'rewind' },
  { c: '⏫', n: 'arrow_double_up' },
  { c: '⏬', n: 'arrow_double_down' },
  { c: '◀️', n: 'arrow_backward' },
  { c: '🔺', n: 'triangle_up' },
  { c: '🔻', n: 'triangle_down' },
  { c: '♾️', n: 'infinity' },
  { c: '♻️', n: 'recycle' },
  { c: '🚸', n: 'children_crossing' },
  { c: '⚜️', n: 'fleur_de_lis' },
  { c: '🔱', n: 'trident' },
  { c: '📛', n: 'name_badge' },
  { c: '🔰', n: 'beginner' },
  { c: '⭕', n: 'o' },
  { c: '🆎', n: 'ab' },
  { c: '🆑', n: 'cl' },
  { c: '🆒', n: 'cool' },
  { c: '🆓', n: 'free' },
  { c: '🆕', n: 'new' },
  { c: '🆖', n: 'ng' },
  { c: '🆗', n: 'ok' },
  { c: '🆘', n: 'sos' },
  { c: '🆙', n: 'up' },
  { c: '🆚', n: 'vs' },
  { c: '©️', n: 'copyright' },
  { c: '®️', n: 'registered' },
  { c: '™️', n: 'tm' },
  { c: '#️⃣', n: 'hash' },
  { c: '*️⃣', n: 'asterisk' },
  { c: '0️⃣', n: 'zero' },
  { c: '1️⃣', n: 'one' },
  { c: '2️⃣', n: 'two' },
  { c: '3️⃣', n: 'three' },
  { c: '4️⃣', n: 'four' },
  { c: '5️⃣', n: 'five' },
  { c: '6️⃣', n: 'six' },
  { c: '7️⃣', n: 'seven' },
  { c: '8️⃣', n: 'eight' },
  { c: '9️⃣', n: 'nine' },
  { c: '🔟', n: 'keycap_ten' },
  { c: '🔢', n: 'numbers' },
  { c: '🔠', n: 'capital_abcd' },
  { c: '🔡', n: 'abcd' },
  { c: '🔣', n: 'symbols' },
  { c: '🔤', n: 'abc' },
]

export interface EmojiMatch {
  entry: EmojiEntry
  score: number
}

export function searchEmojis(query: string, limit = 50): EmojiMatch[] {
  const q = query.toLowerCase().trim()
  if (!q) {
    return EMOJIS.slice(0, limit).map((entry) => ({ entry, score: 0 }))
  }
  const matches: EmojiMatch[] = []
  for (const entry of EMOJIS) {
    let score = 0
    if (entry.n === q) score = 100
    else if (entry.n.startsWith(q)) score = 80
    else if (entry.n.includes(q)) score = 50
    else if (entry.k?.some((kw) => kw === q)) score = 70
    else if (entry.k?.some((kw) => kw.startsWith(q))) score = 40
    else if (entry.k?.some((kw) => kw.includes(q))) score = 20
    if (score > 0) matches.push({ entry, score })
  }
  matches.sort((a, b) => b.score - a.score || a.entry.n.length - b.entry.n.length)
  return matches.slice(0, limit)
}
